### ISSUE TITLE
Problems rendering dextormetorphan examples

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/sbmlutils#275]
```
Traceback (most recent call last):
  File "/home/mkoenig/envs/sbmlutils/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 369, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/mkoenig/envs/sbmlutils/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
    return await self.app(scope, receive, send)
  File "/home/mkoenig/envs/sbmlutils/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/home/mkoenig/envs/sbmlutils/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/mkoenig/envs/sbmlutils/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/mkoenig/envs/sbmlutils/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/mkoenig/envs/sbmlutils/lib/python3.8/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/mkoenig/envs/sbmlutils/lib/python3.8/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/home/mkoenig/envs/sbmlutils/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/mkoenig/envs/sbmlutils/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/mkoenig/envs/sbmlutils/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/mkoenig/envs/sbmlutils/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/home/mkoenig/envs/sbmlutils/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/home/mkoenig/envs/sbmlutils/lib/python3.8/site-packages/fastapi/routing.py", line 219, in app
    raw_response = await run_endpoint_function(
  File "/home/mkoenig/envs/sbmlutils/lib/python3.8/site-packages/fastapi/routing.py", line 152, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/mkoenig/git/sbmlutils/src/sbmlutils/report/api.py", line 57, in upload_sbml
    content = _content_for_source(source=path)
  File "/home/mkoenig/git/sbmlutils/src/sbmlutils/report/api.py", line 103, in _content_for_source
    info = SBMLDocumentInfo.from_sbml(source=source)
  File "/home/mkoenig/git/sbmlutils/src/sbmlutils/report/sbmlinfo.py", line 61, in from_sbml
    return SBMLDocumentInfo(doc=doc)
  File "/home/mkoenig/git/sbmlutils/src/sbmlutils/report/sbmlinfo.py", line 55, in __init__
    self.info = self.create_info()
  File "/home/mkoenig/git/sbmlutils/src/sbmlutils/report/sbmlinfo.py", line 83, in create_info
    model = self.model_dict(self.doc.getModel())
  File "/home/mkoenig/git/sbmlutils/src/sbmlutils/report/sbmlinfo.py", line 101, in model_dict
    rules = self.rules(model=model)
  File "/home/mkoenig/git/sbmlutils/src/sbmlutils/report/sbmlinfo.py", line 678, in rules
    d["derivedUnits"] = udef_to_latex(
  File "/home/mkoenig/git/sbmlutils/src/sbmlutils/report/units.py", line 39, in udef_to_latex
    latex = astnode_to_latex(astnode, model=model)
  File "/home/mkoenig/git/sbmlutils/src/sbmlutils/report/mathml.py", line 353, in astnode_to_latex
    expr = astnode_to_expression(astnode, model=model)
  File "/home/mkoenig/git/sbmlutils/src/sbmlutils/report/mathml.py", line 83, in astnode_to_expression
    return formula_to_expression(formula, model=model)
  File "/home/mkoenig/git/sbmlutils/src/sbmlutils/report/mathml.py", line 132, in formula_to_expression
    ast_node = formula_to_astnode(formula, model=model)
  File "/home/mkoenig/git/sbmlutils/src/sbmlutils/report/mathml.py", line 47, in formula_to_astnode
    raise ValueError(
ValueError: Formula could not be parsed: 'None'.
Error when parsing input '' at position 0:  NULL input.
INFO:     127.0.0.1:41068 - "POST /sbml HTTP/1.1" 500 Internal Server Error

```
Adding the models in a minute.

**Comment by sankha555** [comment]
Fixed in latest commit 2f7ed57
